trials:
  - pipeline: *pipe_default
    parameters:
      estimator:
        cls: sklearn.ensemble.AdaBoostRegressor
        parameters:
          random_state: 1
          base_estimator:
            cls: sklearn.ensemble.VotingRegressor
            parameters:
              n_jobs: -1
              weights: [ 0.25, 0.75, 0.25 ]
              estimators:
                - [ 'RF', {
                  cls: sklearn.ensemble.RandomForestRegressor,
                  parameters: {
                    n_estimators: 1024,
                    max_depth: 128,
                    max_features: 20,
                    n_jobs: -1,
                  }}]
                - [ 'GBR', {
                  cls: sklearn.ensemble.GradientBoostingRegressor,
                  parameters: {
                    loss: 'ls',
                    learning_rate: 0.03,
                    n_estimators: 300,
                    criterion: 'friedman_mse',
                    max_depth: 7,
                    max_features: 'sqrt',
                  }}]
                - [ 'Compose', {
                  cls: smp.models.model.Model,
                  parameters: {
                    estimator_regressor: {
                      cls: sklearn.ensemble.GradientBoostingRegressor,
                      parameters: {
                        loss: 'ls',
                        learning_rate: 0.03,
                        n_estimators: 300,
                        criterion: 'friedman_mse',
                        max_depth: 7,
                        max_features: 'sqrt'
                      }
                    },
                    linkage: 'ward',
                    weight: 2.45,
                    n_neighbors: 9,
                    n_clusters: 7
                  }}]

      param_grid:
        n_estimators: [50]
        learning_rate: [0.001]