trials:
  - pipeline: *pipe_default
    parameters:
      estimator:
        cls: smp.models.model.Model
        parameters:
          estimator_regressor:
            cls: sklearn.ensemble.GradientBoostingRegressor
            parameters:
              loss: 'ls'
              learning_rate: 0.03
              n_estimators: 300
              criterion: 'friedman_mse'
              max_depth:  7
              max_features: 'sqrt'
      param_grid:
        linkage:
          - 'ward'
        weight: [2.4, 2.45, 2.5]
        n_neighbors: [11, 12, 13]
        n_clusters: [ 5, 6, 7]
