trials:

  - pipeline: *pipe_default
    parameters:
      estimator:
        cls: sklearn.ensemble.GradientBoostingRegressor
        parameters: {}
      param_grid:
        loss: ['ls']
        learning_rate: [0.2, 0.1, 0.05]
        n_estimators: [64, 128, 256]
        criterion: ['friedman_mse', 'mse', 'mae']
        max_depth: [3, 8, 16, 32, 64, 128]
        max_features: ['auto', 'sqrt', 'log2']
