trials:

  - pipeline: *pipe_default
    parameters:
      estimator:
        cls: sklearn.ensemble.VotingRegressor
        parameters:
          estimators:
            - [ 'RF', {
              cls: sklearn.ensemble.RandomForestRegressor,
              parameters: {
                n_estimators: 512,
                max_depth: 64,
                max_features: 16,
                random_state: 1
              }
            }
            ]
            - [ 'GBR', {
              cls: sklearn.ensemble.GradientBoostingRegressor,
              parameters: {
                 loss: 'ls',
                 learning_rate: 0.03,
                 n_estimators: 300,
                 criterion: 'friedman_mse',
                 max_depth: 7,
                 max_features: 'sqrt',
                 random_state: 2
              }
            }
            ]
            - ['Compose', {
              cls: smp.models.model.Model,
              parameters: {
                estimator_regressor: {
                  cls: sklearn.ensemble.GradientBoostingRegressor,
                  parameters: {
                    loss: 'ls',
                    learning_rate: 0.03,
                    n_estimators: 300,
                    criterion: 'friedman_mse',
                    max_depth: 7,
                    max_features: 'sqrt'
                  }
                },
                linkage: 'ward',
                weight: 2.45,
                n_neighbors: 9,
                n_clusters: 7,
              }
            }
            ]
          n_jobs: -1
      param_grid:
        weights:
          - [0.25, 0.25, 0.75]

